# Generated by Django 4.2.7 on 2024-01-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='U_name',
        ),
    ]
