# Generated by Django 4.2.7 on 2024-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_v_c_about_v_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='extra',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
