# Generated by Django 4.2.7 on 2024-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_time',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='v_c',
            field=models.CharField(max_length=500),
        ),
    ]
