# Generated by Django 4.2.7 on 2024-01-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_about_date_time_alter_about_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='extra',
        ),
    ]
