# Generated by Django 4.2.7 on 2024-01-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='no_digital_awards',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='no_exp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='no_happy_customers',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='no_project_finished',
            field=models.CharField(max_length=50),
        ),
    ]
