# Generated by Django 4.2.7 on 2024-01-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_about_date_time_alter_about_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='v_c',
            new_name='vf_c',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='v_status',
            new_name='vf_status',
        ),
    ]
