# Generated by Django 4.2.7 on 2024-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_vf_c_about_v_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='v_c',
            field=models.CharField(max_length=500),
        ),
    ]
