# Generated by Django 4.2.7 on 2024-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_about_description_alter_about_v_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='password',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
