# Generated by Django 4.2.7 on 2024-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_about_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
