# Generated by Django 4.2.7 on 2024-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_about_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
